### ISSUE TITLE
Email order of threaded emails

### ISSUE THREAD

**Issue by simsclub** [cixonline/ameol#1]
If sorting by Name, Size or Subject, the sequence number should be used as a secondary sort key.

**Comment by cixonline** [comment]
Should be an easy change. Look at TopicWnd.c - MsgViewWnd_OnCompareItem, If, after comparing the name, size or subject, nSort == 0 then return msginfo1.dwMsg < msginfo2.dwMsg ? -1 : 1.

**Comment by cixonline** [comment]
Now fixed in 2.65.
